// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package server

import (
	"context"

	"hnchain/reply/rpc/internal/logic"
	"hnchain/reply/rpc/internal/svc"
	"hnchain/reply/rpc/reply"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	reply.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) Comments(ctx context.Context, in *reply.CommentsReq) (*reply.CommentsRsp, error) {
	l := logic.NewCommentsLogic(ctx, s.svcCtx)
	return l.Comments(in)
}
