// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package replyclient

import (
	"context"

	"hnchain/reply/rpc/reply"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentItem = reply.CommentItem
	CommentsReq = reply.CommentsReq
	CommentsRsp = reply.CommentsRsp

	Reply interface {
		Comments(ctx context.Context, in *CommentsReq, opts ...grpc.CallOption) (*CommentsRsp, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) Comments(ctx context.Context, in *CommentsReq, opts ...grpc.CallOption) (*CommentsRsp, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.Comments(ctx, in, opts...)
}
