//分组 goctl rpc protoc product.proto --go_out=. --go-grpc_out=. --zrpc_out=. -m
//goctl rpc protoc product.proto --go_out=. --go-grpc_out=. --zrpc_out=.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: product.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Product_Product_FullMethodName              = "/product.Product/Product"
	Product_Products_FullMethodName             = "/product.Product/Products"
	Product_ProductList_FullMethodName          = "/product.Product/ProductList"
	Product_OperationProducts_FullMethodName    = "/product.Product/OperationProducts"
	Product_UpdateProductStock_FullMethodName   = "/product.Product/UpdateProductStock"
	Product_CheckAndUpdateStock_FullMethodName  = "/product.Product/CheckAndUpdateStock"
	Product_CheckProductStock_FullMethodName    = "/product.Product/CheckProductStock"
	Product_RollbackProductStock_FullMethodName = "/product.Product/RollbackProductStock"
	Product_DecrStock_FullMethodName            = "/product.Product/DecrStock"
	Product_DecrStockRevert_FullMethodName      = "/product.Product/DecrStockRevert"
	Product_CategoryList_FullMethodName         = "/product.Product/CategoryList"
	Product_ProductRecommends_FullMethodName    = "/product.Product/ProductRecommends"
)

// ProductClient is the client API for Product service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductClient interface {
	// 查询产品信息
	Product(ctx context.Context, in *ProductItemReq, opts ...grpc.CallOption) (*ProductItem, error)
	// 查询集合的商品信息
	Products(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*ProductRsp, error)
	// 查询指定分类的商品分页
	ProductList(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListRsp, error)
	// 刷新运营产品缓存
	OperationProducts(ctx context.Context, in *OperationProductsReq, opts ...grpc.CallOption) (*OperationProductsRsp, error)
	// 根据目标量，增加库存
	UpdateProductStock(ctx context.Context, in *UpdateProductStockReq, opts ...grpc.CallOption) (*UpdateProductStockRsp, error)
	// 扣减库存(缓存)
	CheckAndUpdateStock(ctx context.Context, in *CheckAndUpdateStockReq, opts ...grpc.CallOption) (*CheckAndUpdateStockRsp, error)
	// 检查库存量
	CheckProductStock(ctx context.Context, in *UpdateProductStockReq, opts ...grpc.CallOption) (*UpdateProductStockRsp, error)
	RollbackProductStock(ctx context.Context, in *UpdateProductStockReq, opts ...grpc.CallOption) (*UpdateProductStockRsp, error)
	// 事务:扣减库存
	DecrStock(ctx context.Context, in *DecrStockReq, opts ...grpc.CallOption) (*DecrStockRsp, error)
	// 事务:扣减库存,再加回去
	DecrStockRevert(ctx context.Context, in *DecrStockReq, opts ...grpc.CallOption) (*DecrStockRsp, error)
	// 根据类父ID,查询分类列表
	CategoryList(ctx context.Context, in *CategoryItemReq, opts ...grpc.CallOption) (*CategoryItemRsp, error)
	// 目标数量的推荐商品
	ProductRecommends(ctx context.Context, in *ProductRecommendReq, opts ...grpc.CallOption) (*ProductRecommendRsp, error)
}

type productClient struct {
	cc grpc.ClientConnInterface
}

func NewProductClient(cc grpc.ClientConnInterface) ProductClient {
	return &productClient{cc}
}

func (c *productClient) Product(ctx context.Context, in *ProductItemReq, opts ...grpc.CallOption) (*ProductItem, error) {
	out := new(ProductItem)
	err := c.cc.Invoke(ctx, Product_Product_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) Products(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*ProductRsp, error) {
	out := new(ProductRsp)
	err := c.cc.Invoke(ctx, Product_Products_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) ProductList(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListRsp, error) {
	out := new(ProductListRsp)
	err := c.cc.Invoke(ctx, Product_ProductList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) OperationProducts(ctx context.Context, in *OperationProductsReq, opts ...grpc.CallOption) (*OperationProductsRsp, error) {
	out := new(OperationProductsRsp)
	err := c.cc.Invoke(ctx, Product_OperationProducts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) UpdateProductStock(ctx context.Context, in *UpdateProductStockReq, opts ...grpc.CallOption) (*UpdateProductStockRsp, error) {
	out := new(UpdateProductStockRsp)
	err := c.cc.Invoke(ctx, Product_UpdateProductStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) CheckAndUpdateStock(ctx context.Context, in *CheckAndUpdateStockReq, opts ...grpc.CallOption) (*CheckAndUpdateStockRsp, error) {
	out := new(CheckAndUpdateStockRsp)
	err := c.cc.Invoke(ctx, Product_CheckAndUpdateStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) CheckProductStock(ctx context.Context, in *UpdateProductStockReq, opts ...grpc.CallOption) (*UpdateProductStockRsp, error) {
	out := new(UpdateProductStockRsp)
	err := c.cc.Invoke(ctx, Product_CheckProductStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) RollbackProductStock(ctx context.Context, in *UpdateProductStockReq, opts ...grpc.CallOption) (*UpdateProductStockRsp, error) {
	out := new(UpdateProductStockRsp)
	err := c.cc.Invoke(ctx, Product_RollbackProductStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) DecrStock(ctx context.Context, in *DecrStockReq, opts ...grpc.CallOption) (*DecrStockRsp, error) {
	out := new(DecrStockRsp)
	err := c.cc.Invoke(ctx, Product_DecrStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) DecrStockRevert(ctx context.Context, in *DecrStockReq, opts ...grpc.CallOption) (*DecrStockRsp, error) {
	out := new(DecrStockRsp)
	err := c.cc.Invoke(ctx, Product_DecrStockRevert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) CategoryList(ctx context.Context, in *CategoryItemReq, opts ...grpc.CallOption) (*CategoryItemRsp, error) {
	out := new(CategoryItemRsp)
	err := c.cc.Invoke(ctx, Product_CategoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) ProductRecommends(ctx context.Context, in *ProductRecommendReq, opts ...grpc.CallOption) (*ProductRecommendRsp, error) {
	out := new(ProductRecommendRsp)
	err := c.cc.Invoke(ctx, Product_ProductRecommends_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServer is the server API for Product service.
// All implementations must embed UnimplementedProductServer
// for forward compatibility
type ProductServer interface {
	// 查询产品信息
	Product(context.Context, *ProductItemReq) (*ProductItem, error)
	// 查询集合的商品信息
	Products(context.Context, *ProductReq) (*ProductRsp, error)
	// 查询指定分类的商品分页
	ProductList(context.Context, *ProductListReq) (*ProductListRsp, error)
	// 刷新运营产品缓存
	OperationProducts(context.Context, *OperationProductsReq) (*OperationProductsRsp, error)
	// 根据目标量，增加库存
	UpdateProductStock(context.Context, *UpdateProductStockReq) (*UpdateProductStockRsp, error)
	// 扣减库存(缓存)
	CheckAndUpdateStock(context.Context, *CheckAndUpdateStockReq) (*CheckAndUpdateStockRsp, error)
	// 检查库存量
	CheckProductStock(context.Context, *UpdateProductStockReq) (*UpdateProductStockRsp, error)
	RollbackProductStock(context.Context, *UpdateProductStockReq) (*UpdateProductStockRsp, error)
	// 事务:扣减库存
	DecrStock(context.Context, *DecrStockReq) (*DecrStockRsp, error)
	// 事务:扣减库存,再加回去
	DecrStockRevert(context.Context, *DecrStockReq) (*DecrStockRsp, error)
	// 根据类父ID,查询分类列表
	CategoryList(context.Context, *CategoryItemReq) (*CategoryItemRsp, error)
	// 目标数量的推荐商品
	ProductRecommends(context.Context, *ProductRecommendReq) (*ProductRecommendRsp, error)
	mustEmbedUnimplementedProductServer()
}

// UnimplementedProductServer must be embedded to have forward compatible implementations.
type UnimplementedProductServer struct {
}

func (UnimplementedProductServer) Product(context.Context, *ProductItemReq) (*ProductItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Product not implemented")
}
func (UnimplementedProductServer) Products(context.Context, *ProductReq) (*ProductRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Products not implemented")
}
func (UnimplementedProductServer) ProductList(context.Context, *ProductListReq) (*ProductListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductList not implemented")
}
func (UnimplementedProductServer) OperationProducts(context.Context, *OperationProductsReq) (*OperationProductsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperationProducts not implemented")
}
func (UnimplementedProductServer) UpdateProductStock(context.Context, *UpdateProductStockReq) (*UpdateProductStockRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductStock not implemented")
}
func (UnimplementedProductServer) CheckAndUpdateStock(context.Context, *CheckAndUpdateStockReq) (*CheckAndUpdateStockRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAndUpdateStock not implemented")
}
func (UnimplementedProductServer) CheckProductStock(context.Context, *UpdateProductStockReq) (*UpdateProductStockRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProductStock not implemented")
}
func (UnimplementedProductServer) RollbackProductStock(context.Context, *UpdateProductStockReq) (*UpdateProductStockRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackProductStock not implemented")
}
func (UnimplementedProductServer) DecrStock(context.Context, *DecrStockReq) (*DecrStockRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrStock not implemented")
}
func (UnimplementedProductServer) DecrStockRevert(context.Context, *DecrStockReq) (*DecrStockRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrStockRevert not implemented")
}
func (UnimplementedProductServer) CategoryList(context.Context, *CategoryItemReq) (*CategoryItemRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryList not implemented")
}
func (UnimplementedProductServer) ProductRecommends(context.Context, *ProductRecommendReq) (*ProductRecommendRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductRecommends not implemented")
}
func (UnimplementedProductServer) mustEmbedUnimplementedProductServer() {}

// UnsafeProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServer will
// result in compilation errors.
type UnsafeProductServer interface {
	mustEmbedUnimplementedProductServer()
}

func RegisterProductServer(s grpc.ServiceRegistrar, srv ProductServer) {
	s.RegisterService(&Product_ServiceDesc, srv)
}

func _Product_Product_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).Product(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_Product_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).Product(ctx, req.(*ProductItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_Products_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).Products(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_Products_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).Products(ctx, req.(*ProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_ProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).ProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_ProductList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).ProductList(ctx, req.(*ProductListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_OperationProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).OperationProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_OperationProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).OperationProducts(ctx, req.(*OperationProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_UpdateProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).UpdateProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_UpdateProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).UpdateProductStock(ctx, req.(*UpdateProductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_CheckAndUpdateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAndUpdateStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).CheckAndUpdateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_CheckAndUpdateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).CheckAndUpdateStock(ctx, req.(*CheckAndUpdateStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_CheckProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).CheckProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_CheckProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).CheckProductStock(ctx, req.(*UpdateProductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_RollbackProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).RollbackProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_RollbackProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).RollbackProductStock(ctx, req.(*UpdateProductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_DecrStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DecrStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_DecrStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DecrStock(ctx, req.(*DecrStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_DecrStockRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DecrStockRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_DecrStockRevert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DecrStockRevert(ctx, req.(*DecrStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_CategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).CategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_CategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).CategoryList(ctx, req.(*CategoryItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_ProductRecommends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).ProductRecommends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_ProductRecommends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).ProductRecommends(ctx, req.(*ProductRecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Product_ServiceDesc is the grpc.ServiceDesc for Product service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Product_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.Product",
	HandlerType: (*ProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Product",
			Handler:    _Product_Product_Handler,
		},
		{
			MethodName: "Products",
			Handler:    _Product_Products_Handler,
		},
		{
			MethodName: "ProductList",
			Handler:    _Product_ProductList_Handler,
		},
		{
			MethodName: "OperationProducts",
			Handler:    _Product_OperationProducts_Handler,
		},
		{
			MethodName: "UpdateProductStock",
			Handler:    _Product_UpdateProductStock_Handler,
		},
		{
			MethodName: "CheckAndUpdateStock",
			Handler:    _Product_CheckAndUpdateStock_Handler,
		},
		{
			MethodName: "CheckProductStock",
			Handler:    _Product_CheckProductStock_Handler,
		},
		{
			MethodName: "RollbackProductStock",
			Handler:    _Product_RollbackProductStock_Handler,
		},
		{
			MethodName: "DecrStock",
			Handler:    _Product_DecrStock_Handler,
		},
		{
			MethodName: "DecrStockRevert",
			Handler:    _Product_DecrStockRevert_Handler,
		},
		{
			MethodName: "CategoryList",
			Handler:    _Product_CategoryList_Handler,
		},
		{
			MethodName: "ProductRecommends",
			Handler:    _Product_ProductRecommends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
